server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:monitoringdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: INFO